INFO 2025-10-20 00:13:30,017 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:14:54,379 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blogging_platform\settings.py changed, reloading.
INFO 2025-10-20 00:14:56,401 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:15:36,958 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:16:44,069 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:19:17,229 autoreload Watching for file changes with StatReloader
WARNING 2025-10-20 00:19:27,249 log Not Found: /
WARNING 2025-10-20 00:19:27,250 basehttp "GET / HTTP/1.1" 404 3535
WARNING 2025-10-20 00:19:27,622 log Not Found: /favicon.ico
WARNING 2025-10-20 00:19:27,625 basehttp "GET /favicon.ico HTTP/1.1" 404 3586
INFO 2025-10-20 00:19:41,214 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-10-20 00:19:41,648 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4188
INFO 2025-10-20 00:19:42,355 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-20 00:19:42,388 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-20 00:19:42,392 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-20 00:19:42,398 basehttp "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-10-20 00:19:42,416 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-20 00:19:42,477 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-20 00:19:42,516 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-10-20 00:19:54,517 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-10-20 00:19:54,637 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 00:19:54,765 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-10-20 00:19:54,803 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-10-20 00:19:54,804 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
WARNING 2025-10-20 00:20:22,857 log Not Found: /
WARNING 2025-10-20 00:20:22,863 basehttp "GET / HTTP/1.1" 404 3535
INFO 2025-10-20 00:21:50,678 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blogging_platform\urls.py changed, reloading.
INFO 2025-10-20 00:21:54,097 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:26:09,199 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:26:17,984 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blogpost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 765, in home_view
    'total_posts': BlogPost.objects.filter(status='published').count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blogpost
ERROR 2025-10-20 00:26:18,020 basehttp "GET / HTTP/1.1" 500 138950
INFO 2025-10-20 00:26:55,659 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 00:26:55,893 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,929 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,942 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:55,977 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,026 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,047 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,053 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,210 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 00:26:56,214 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
ERROR 2025-10-20 00:27:02,090 log Internal Server Error: /admin/blog/blogpost/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 2024, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\options.py", line 867, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.queryset = self.get_queryset(request)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 545, in get_queryset
    ) = self.get_filters(request)
        ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\views\main.py", line 216, in get_filters
    spec = field_list_filter_class(
        field,
    ...<4 lines>...
        field_path=field_path,
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 217, in create
    return list_filter_class(
        field, request, params, model, model_admin, field_path=field_path
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 232, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\admin\filters.py", line 273, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 1083, in get_choices
    (choice_func(x), str(x)) for x in qs
                                      ^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_category
ERROR 2025-10-20 00:27:02,127 basehttp "GET /admin/blog/blogpost/ HTTP/1.1" 500 223287
INFO 2025-10-20 00:45:04,860 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:45:22,813 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: blog_blogpost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 765, in home_view
    'total_posts': BlogPost.objects.filter(status='published').count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 604, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: blog_blogpost
ERROR 2025-10-20 00:45:22,850 basehttp "GET / HTTP/1.1" 500 138950
INFO 2025-10-20 00:47:28,685 autoreload Watching for file changes with StatReloader
ERROR 2025-10-20 00:47:37,973 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 770, in home_view
    return render(request, 'blog/home.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1610, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 766, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 86, in pre_sql_setup
    order_by = self.get_order_by()
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 490, in get_order_by
    for expr, is_ref in self._order_by_pairs():
                        ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 473, in _order_by_pairs
    yield from self.find_ordering_name(
               ~~~~~~~~~~~~~~~~~~~~~~~^
        field,
        ^^^^^^
        self.query.get_meta(),
        ^^^^^^^^^^^^^^^^^^^^^^
        default_order=default_order,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1120, in find_ordering_name
    (OrderBy(transform_function(t, alias), descending=descending), False)
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1924, in transform
    return self.try_transform(wrapped, name)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\db\models\sql\query.py", line 1458, in try_transform
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Unsupported lookup 'count' for BigAutoField or join on the field not permitted, perhaps you meant contains?
ERROR 2025-10-20 00:47:38,009 basehttp "GET / HTTP/1.1" 500 216793
INFO 2025-10-20 00:48:28,512 autoreload C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py changed, reloading.
INFO 2025-10-20 00:48:30,818 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:48:58,767 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:49:25,304 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:50:28,505 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 00:50:37,193 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 00:50:37,777 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 13721
INFO 2025-10-20 00:50:37,791 basehttp "GET /static/blog/js/main.js HTTP/1.1" 200 1633
INFO 2025-10-20 00:50:37,792 basehttp "GET /static/blog/css/components.css HTTP/1.1" 200 5938
INFO 2025-10-20 01:01:11,312 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 01:01:16,574 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:01:16,865 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 01:01:16,879 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
INFO 2025-10-20 01:01:17,086 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 13909
ERROR 2025-10-20 01:01:49,936 log Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 1029, in post_create_view
    return render(request, 'blog/post_form.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_form.html
ERROR 2025-10-20 01:01:49,953 basehttp "GET /create/ HTTP/1.1" 500 97952
INFO 2025-10-20 01:02:17,975 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 01:02:18,062 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,091 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,092 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,109 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,112 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,118 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,123 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,171 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:02:18,172 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:02:40,245 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 01:04:31,923 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:04:32,273 basehttp "GET /static/blog/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:09:01,946 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:09:02,210 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 01:09:02,239 basehttp "GET /static/blog/css/base.css HTTP/1.1" 200 15961
INFO 2025-10-20 01:09:02,274 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
INFO 2025-10-20 01:11:13,279 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 01:14:09,287 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 01:14:10,397 basehttp "GET /static/blog/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:10,646 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:10,888 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
INFO 2025-10-20 01:14:38,700 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 01:14:39,539 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:39,748 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:39,945 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,094 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,232 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,308 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,408 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,559 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:14:40,560 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-10-20 01:15:09,409 basehttp "GET /admin/blog/blogpost/add/ HTTP/1.1" 200 29601
INFO 2025-10-20 01:15:09,866 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-20 01:15:11,197 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-10-20 01:15:11,449 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-10-20 01:15:11,465 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-10-20 01:15:11,470 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-10-20 01:15:11,622 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 11973
INFO 2025-10-20 01:15:11,722 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-10-20 01:15:11,784 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-10-20 01:15:11,946 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15845
INFO 2025-10-20 01:15:11,960 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-10-20 01:15:11,962 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-10-20 01:15:12,098 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-10-20 01:15:12,353 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-10-20 01:15:12,739 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-10-20 01:15:12,828 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-10-20 01:15:13,084 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-10-20 01:15:13,208 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-10-20 01:15:13,410 basehttp "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2025-10-20 01:15:13,465 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-10-20 01:15:13,949 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-10-20 01:15:14,058 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-10-20 01:15:14,076 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-10-20 01:15:14,077 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-10-20 08:48:33,756 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 08:49:23,324 autoreload Watching for file changes with StatReloader
INFO 2025-10-20 08:49:28,984 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 08:49:29,272 basehttp "GET /static/blog/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 08:49:29,272 basehttp "GET /static/blog/css/components.css HTTP/1.1" 304 0
INFO 2025-10-20 08:49:29,375 basehttp "GET /static/blog/js/main.js HTTP/1.1" 304 0
WARNING 2025-10-20 08:49:30,516 log Not Found: /favicon.ico
WARNING 2025-10-20 08:49:30,591 basehttp "GET /favicon.ico HTTP/1.1" 404 7769
ERROR 2025-10-20 08:49:36,636 log Internal Server Error: /create/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 1029, in post_create_view
    return render(request, 'blog/post_form.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_form.html
ERROR 2025-10-20 08:49:36,648 basehttp "GET /create/ HTTP/1.1" 500 95942
INFO 2025-10-20 08:50:05,043 basehttp "GET / HTTP/1.1" 200 11574
INFO 2025-10-20 08:50:19,754 basehttp "GET /posts HTTP/1.1" 301 0
ERROR 2025-10-20 08:50:19,960 log Internal Server Error: /posts/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 817, in post_list_view
    return render(request, 'blog/post_list.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_list.html
ERROR 2025-10-20 08:50:19,987 basehttp "GET /posts/ HTTP/1.1" 500 92827
INFO 2025-10-20 08:50:35,117 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 08:50:35,206 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,208 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,208 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,209 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,211 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,219 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,220 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,245 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-10-20 08:50:35,249 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,124 basehttp "GET /admin/authtoken/tokenproxy/add/ HTTP/1.1" 200 15854
INFO 2025-10-20 08:50:41,232 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,232 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,233 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,233 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,233 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,280 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,351 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-20 08:50:41,373 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,377 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,384 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,398 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,399 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,491 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2025-10-20 08:50:41,494 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-10-20 08:50:47,688 basehttp "GET /admin/auth/user/add/?_to_field=id&_popup=1 HTTP/1.1" 200 8111
INFO 2025-10-20 08:50:47,765 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-20 08:50:48,013 basehttp "GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
INFO 2025-10-20 08:50:48,063 basehttp "GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
INFO 2025-10-20 08:51:05,448 basehttp "GET /admin/auth/group/add/ HTTP/1.1" 200 21876
INFO 2025-10-20 08:51:05,520 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
INFO 2025-10-20 08:51:05,521 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
INFO 2025-10-20 08:51:05,525 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-10-20 08:51:05,586 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-10-20 08:51:05,588 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
INFO 2025-10-20 08:51:20,480 basehttp "GET /admin/auth/user/add/ HTTP/1.1" 200 18626
INFO 2025-10-20 08:51:20,561 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
WARNING 2025-10-20 08:51:49,385 log Not Found: /blog
WARNING 2025-10-20 08:51:49,386 basehttp "GET /blog HTTP/1.1" 404 7748
INFO 2025-10-20 08:52:13,483 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-10-20 08:52:13,538 basehttp "GET /admin/ HTTP/1.1" 200 14906
INFO 2025-10-20 08:52:33,611 basehttp "GET / HTTP/1.1" 200 11574
ERROR 2025-10-20 08:52:36,778 log Internal Server Error: /api-docs/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 1105, in api_docs_view
    return render(request, 'blog/api_docs.html')
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/api_docs.html
ERROR 2025-10-20 08:52:36,781 basehttp "GET /api-docs/ HTTP/1.1" 500 89348
ERROR 2025-10-20 08:52:47,552 log Internal Server Error: /my-posts/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 994, in my_posts_view
    return render(request, 'blog/my_posts.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/my_posts.html
ERROR 2025-10-20 08:52:47,564 basehttp "GET /my-posts/ HTTP/1.1" 500 96578
ERROR 2025-10-20 08:53:16,741 log Internal Server Error: /posts/
Traceback (most recent call last):
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\blog\views.py", line 817, in post_list_view
    return render(request, 'blog/post_list.html', context)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\backendCapstoneProject\blogging_platform\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_list.html
ERROR 2025-10-20 08:53:16,746 basehttp "GET /posts/ HTTP/1.1" 500 92978
INFO 2025-10-20 08:54:08,023 basehttp "GET /api HTTP/1.1" 301 0
INFO 2025-10-20 08:54:08,203 basehttp "GET /api/ HTTP/1.1" 200 7111
INFO 2025-10-20 08:54:08,297 basehttp "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2025-10-20 08:54:08,300 basehttp "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
INFO 2025-10-20 08:54:08,305 basehttp "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2025-10-20 08:54:08,317 basehttp "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2025-10-20 08:54:08,361 basehttp "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
INFO 2025-10-20 08:54:08,418 basehttp "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2025-10-20 08:54:08,419 basehttp "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
INFO 2025-10-20 08:54:08,473 basehttp "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2025-10-20 08:54:08,478 basehttp "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
INFO 2025-10-20 08:54:08,556 basehttp "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2025-10-20 08:54:08,608 basehttp "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2025-10-20 08:54:08,608 basehttp "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
INFO 2025-10-20 08:54:22,127 basehttp "GET /api/posts/ HTTP/1.1" 200 16748
INFO 2025-10-20 08:54:22,538 basehttp "GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
INFO 2025-10-20 08:54:30,775 basehttp "GET /api/ HTTP/1.1" 200 7111
WARNING 2025-10-20 08:55:20,933 log Not Found: /api/user
WARNING 2025-10-20 08:55:20,936 basehttp "GET /api/user HTTP/1.1" 404 49611
INFO 2025-10-20 08:55:33,493 basehttp "GET /api/users HTTP/1.1" 301 0
INFO 2025-10-20 08:55:33,695 basehttp "GET /api/users/ HTTP/1.1" 200 13503
INFO 2025-10-20 08:56:02,060 basehttp "GET /api/users/?format=api HTTP/1.1" 200 13651
INFO 2025-10-20 08:56:06,306 basehttp "GET /api/users/?format=json HTTP/1.1" 200 194
